# Generated by Django 2.2 on 2020-04-24 17:45

from django.db import migrations, models
import django.db.models.deletion
import flash.product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200407_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='products_logo', validators=[flash.product.validators.validate_file_size, flash.product.validators.validate_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization.Organization'),
        ),
    ]
