# Generated by Django 2.2 on 2020-04-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20200407_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filials', to='organization.Organization'),
        ),
    ]
