# Generated by Django 2.2 on 2020-04-16 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200416_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organization.Organization'),
        ),
    ]
