# Generated by Django 2.2 on 2020-04-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Filial'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Product'),
        ),
    ]
