# Generated by Django 2.2 on 2020-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0002_auto_20200414_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
